In [15]:
import numpy as np
import pandas as pd

In [19]:
# Q1. Create a 1D array of numbers from 1 to 10
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# Q2. Reshape it into 2D array with dimension 2*5

a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
# Q3. Create a 2D array. calculate and print sum, mean, std deviation, min, maz of the array

In [44]:
x= np.arange(1,101,5)
x= x.reshape(2,10)

In [55]:
print(f"sum is:{x.sum()}")
print(f"mean is:{x.mean()}")
print(f"std is:{x.std()}")
print(f"min is:{x.min()}")
print(f"max is:{x.max()}")

sum is:970
mean is:48.5
std is:28.83140648667699
min is:1
max is:96


In [39]:
# Numpy pratice

[[ 1  6 11 16 21 26 31 36 41 46]
 [51 56 61 66 71 76 81 86 91 96]]


In [37]:
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [12]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
print(np.__version__)

1.24.3


In [15]:
arr = np.array(42)

print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [21]:
ff = [[1, 2 , 3],[5,5, 6]]
print(type(ff))

<class 'list'>


In [24]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [25]:
arr = np.array([1, 2, 3, 4], ndmin=5)

printtype((arr))
print('shape of array :', arr.shape)

NameError: name 'printtype' is not defined

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,14,15,16,17,18,19])

newarr = arr.reshape(3,2,-2)
newarr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[14, 15, 16],
        [17, 18, 19]]])

In [47]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)
print(type(myvar))
print(type(mydataset))
print(mydataset)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
<class 'pandas.core.frame.DataFrame'>
<class 'dict'>
{'cars': ['BMW', 'Volvo', 'Ford'], 'passings': [3, 7, 2]}


In [49]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

df

calories  duration
0       420        50
1       380        40
2       390        45

In [51]:
df.loc[0] 

calories    420
duration     50
Name: 0, dtype: int64

In [5]:
data = np.loadtxt("m.txt")
data

array([ 45. , 100. , 150. , 160. , 140. ,  20.5])

In [6]:

#Flattening
a = np.array([[1,2,3], [4,5,6]]) # 2D array
a.ravel() #return a contigous flattened array, Converts 2D to 1-D array

array([1, 2, 3, 4, 5, 6])

In [8]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [10]:
a = np.arange(4*3*2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
4*3*2

24

In [14]:
a.sum()

276

In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame({"id":[1,2,3,4,5,6,7,8,9],"name":['Olivia', 'Aditya', 'N/A', 'Isabell', 'Dominic', 'Tyler', 'Samuel', 'Daniel', 'Jeremy'],
                  "Age":[20, 25, 15, 10, 30, 65, 35, 18, 23],
                  "Product":[101,0, 106, 0, 103, 104,0 ,0 , 107],
                  "Purchased":['Watch','N/A', 'Oil', 'N/A', 'Shoes', 'Smartphone','N/A' ,'N/A' , 'Laptop'],
                  "City":['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Chennai', 'Delhi', 'Kolkata', 'Delhi', 'Mumbai'],
                  "Sale_Amount":[10000,150000,2000,30000,15000,16000,15000,25000,48000]})
df


id     name  Age  Product   Purchased       City  Sale_Amount
0   1   Olivia   20      101       Watch     Mumbai        10000
1   2   Aditya   25        0         N/A      Delhi       150000
2   3      N/A   15      106         Oil  Bangalore         2000
3   4  Isabell   10        0         N/A    Chennai        30000
4   5  Dominic   30      103       Shoes    Chennai        15000
5   6    Tyler   65      104  Smartphone      Delhi        16000
6   7   Samuel   35        0         N/A    Kolkata        15000
7   8   Daniel   18        0         N/A      Delhi        25000
8   9   Jeremy   23      107      Laptop     Mumbai        48000

In [ ]:
df.